language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
  - pip install python-dp
  - LD_LIBRARY_PATH=/usr/local/lib64/:$LD_LIBRARY_PATH
  - export LD_LIBRARY_PATH
# command to run tests
script: python3 ./benchmark.py || python ./benchmark.py
